config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  resources :communities do
    resources :posts do
      resources :likeds
      resources :comments
    end
    resources :community_participants
  end

  put '/users/:id/update', to: 'users#update', as: 'update_user'

  get 'administration', to: 'administration#index'
  get 'administration/communities', to: 'administration#list_communities'
  patch 'administration/community/add_modder', to: 'administration#add_modder_to_community'
  get 'administration/admins', to: 'administration#list_admins'
  patch 'administration/admins/give_admin', to: 'administration#give_admin_permissions'
  patch 'administration/admins/remove_admin', to: 'administration#remove_admin_permissions'

  devise_for :users, controllers: {
    passwords: 'passwords'
  }
  
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  get 'dashboard', to: 'dashboard#index', as: 'dashboard'
  get 'dashboard/my_contents', to: 'dashboard#my_contents', as: 'my_contents'
  get 'dashboard/find_communities', to: 'dashboard#find_communities', as: 'find_communities'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end

  def my_contents
    @my_communities = current_user.communities
    @my_liked_ads = current_user.likeds
    respond_to do |format|
        format.html
    end
  end

  def find_communities
    @communities = Community.where.not(id: current_user.communities.pluck(:id))
    respond_to do |format|
        format.html
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/find_communities.html.haml
= turbo_frame_tag "tab_content" do
  .lists
    .my-communities
      %h2.title
        = 'Encontrar comunidades'
      .cards-list
        - if @communities.blank?
          %p= 'Não encontramos nenhuma comunidade em que você possa participar'
        - else
          - @communities.each do |community|
            .card{class: "community#{community.id}"}
              .card-image
                = image_tag resource_image(community)
              .card-content
                %h3= community.name
                %p= "Total de membros: #{community&.community_participants&.count.to_i}"
                %br
                = form_tag community_community_participants_path(community_id: community.id, user_id: current_user.id), method: :post, data: { turbo: false } do
                  = submit_tag 'Participar'

app/views/dashboard/index.html.haml
%ul.tabs
  .dashboard
    .tabs-row
      %h1.tab.active
        = link_to "Meu espaço", my_contents_path, class: "nav-link", data: {"turbo-frame": :"tab_content"}
      %h1.tab
        = link_to "Encontrar comunidades", find_communities_path, class: "nav-link", data: {"turbo-frame": :"tab_content"}

= turbo_frame_tag "tab_content", src: my_contents_path

:javascript
  document.addEventListener("turbo:load", function() {
    const tabs = document.querySelectorAll(".tabs .tab");
    const tabContents = document.querySelectorAll(".tab-content");

    tabs.forEach((tab, index) => {
      tab.addEventListener("click", () => {
        tabs.forEach((tab) => tab.classList.remove("active"));
        tab.classList.add("active");

        tabContents.forEach((tabContent) =>
          tabContent.classList.remove("active")
        );
        tabContents[index].classList.add("active");
      });
    });
  });

app/views/dashboard/my_contents.html.haml
= turbo_frame_tag "tab_content" do
  .lists
    .my-communities
      %h2.title
        = t('Minhas comunidades')
      .cards-list
        - if @my_communities.blank?
          %p= 'Você ainda não faz parte de nenhuma comunidade'
        - else
          - @my_communities.each do |community|
            .card{onclick: "window.location='#{community_path(community)}'"}
              .card-image
                = image_tag resource_image(community)
              .card-content
                %h3= community.name
                %p= "Total de membros: #{community&.community_participants&.count.to_i}"
    .my-liked-ads
      %h2.title
        = t('Anúncios favoritados')
      .cards-list
        - if @my_liked_ads.blank?
          %p= 'Você ainda não favoritou nenhum anúncio'
        - else
          - @my_liked_ads.each do |ad|
            .card{onclick: "window.location='#{community_post_path(ad.community, ad.post)}'"}
              .card-image
                - if ad.post.images.attached?
                  = image_tag ad.post.images.first
                - else
                  = image_tag "post_default.png"
              .card-content
                %h3= ad.post.title
                %p= ad.post.description