config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  resources :communities do
    resources :posts do
      resources :likeds
      resources :comments
    end
    resources :community_participants
  end

  put '/users/:id/update', to: 'users#update', as: 'update_user'

  get 'administration', to: 'administration#index'
  get 'administration/communities', to: 'administration#list_communities'
  patch 'administration/community/add_modder', to: 'administration#add_modder_to_community'
  get 'administration/admins', to: 'administration#list_admins'
  patch 'administration/admins/give_admin', to: 'administration#give_admin_permissions'
  patch 'administration/admins/remove_admin', to: 'administration#remove_admin_permissions'

  devise_for :users, controllers: {
    passwords: 'passwords'
  }
  
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  get 'dashboard', to: 'dashboard#index', as: 'dashboard'
  get 'dashboard/my_contents', to: 'dashboard#my_contents', as: 'my_contents'
  get 'dashboard/find_communities', to: 'dashboard#find_communities', as: 'find_communities'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :set_post
  before_action :set_community

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      respond_to do |format|
        format.html { redirect_to community_post_url(@community, @post), locals: { comment: @comment }}
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to community_post_comment_url(@community, @post, @comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy
    redirect_to community_post_url(@community, @post)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_post
      @post = Post.find(params[:post_id])
    end

    def set_community
      @community = Community.find(params[:community_id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:description).merge(user_id: current_user.id, post_id: @post.id)
    end
    
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
.data-card.comment
  .user-info
    = image_tag resource_image(comment.user), class: "medium-pfp"
    %h2.name
      = comment.user.full_name
  .comment-content
    = comment.description

app/views/comments/_form.html.haml
= form_with(model: [@community, @post, comment]) do |form|
  - if comment.errors.any?
    %div{:style => "color: red"}
      %h2
        = pluralize(comment.errors.count, "error")
        prohibited this comment from being saved:
      %ul
        - comment.errors.each do |error|
          %li= error.full_message
  %div
    = form.label :description, style: "display: block"
    = form.text_area :description
  %div
    = form.submit

app/views/comments/edit.html.haml
%h1 Editing comment
= render "form", comment: @comment
%br/
%div
  = link_to "Show this comment", community_post_comment_path(@community, @post, @comment)
  
  = link_to "Back to comments", community_post_comment_path(@community, @post)

app/views/comments/index.html.haml
%p{:style => "color: green"}= notice
%h1 Comments
#comments
  - @comments.each do |comment|
    = render comment
    %p
      = link_to "Show this comment", community_post_comment_path(@community, @post, comment)
= link_to "New comment", new_community_post_comment_path(@community, @post)
= link_to "Voltar para posts" , community_post_path(@community, @post)
```

app/views/comments/new.html.haml
%h1 New comment
= render "form", comment: @comment
%br/
%div
  = link_to "Back to comments", community_post_comments_path(@community, @post)

app/views/comments/show.html.haml
%p{:style => "color: green"}= notice
= render @comment
%div
  = link_to "Edit this comment", edit_community_post_comment_path(@community, @post, @comment)
  
  = link_to "Back to comments", community_post_comments_path(@community, @post)
  
  = button_to "Destroy this comment", community_post_comment_path(@community, @post, @comment), method: :delete