config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  resources :communities do
    resources :posts do
      resources :likeds
      resources :comments
    end
    resources :community_participants
  end

  put '/users/:id/update', to: 'users#update', as: 'update_user'

  get 'administration', to: 'administration#index'
  get 'administration/communities', to: 'administration#list_communities'
  patch 'administration/community/add_modder', to: 'administration#add_modder_to_community'
  get 'administration/admins', to: 'administration#list_admins'
  patch 'administration/admins/give_admin', to: 'administration#give_admin_permissions'
  patch 'administration/admins/remove_admin', to: 'administration#remove_admin_permissions'

  devise_for :users, controllers: {
    passwords: 'passwords'
  }
  
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  get 'dashboard', to: 'dashboard#index', as: 'dashboard'
  get 'dashboard/my_contents', to: 'dashboard#my_contents', as: 'my_contents'
  get 'dashboard/find_communities', to: 'dashboard#find_communities', as: 'find_communities'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :community_participant
  has_many :likeds, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many_attached :images
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :set_community
  before_action :set_community_participant

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @community = Community.find(params[:community_id])
    @post = Post.find(params[:id])
    @comment = Comment.new
    @liked = Liked.find_by(post_id: @post.id, user_id: @community_participant.user.id) || Liked.new
    @back_path = community_path(@community)
  end

  # GET /posts/new
  def new
    @post = Post.new
    @back_path = community_path(@community)
  end

  # GET /posts/1/edit
  def edit
    @back_path = community_post_path(@community, @post)
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to community_post_url(@community, @post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to community_post_url(@community, @post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to community_posts_url(@community), notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def set_community
      @community = Community.find(params[:community_id])
    end

    def set_community_participant
      @community_participant = CommunityParticipant.where(community_id: params[:community_id], user_id: current_user.id).first
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, images: []).merge(community_participant_id: @community_participant.id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= form_with(model: [@community, post]) do |form|
  - if post.errors.any?
    %div{:style => "color: red"}
      %h2
        = pluralize(post.errors.count, "error")
        prohibited this post from being saved:
      %ul
        - post.errors.each do |error|
          %li= error.full_message
  %div
    .field
      = form.label "Título"
      %br/
      = form.text_area :title, class: "input", required: true
    .field
      = form.label "Descrição"
      %br/
      = form.text_area :description, class: "input", required: true
    .field
      = form.label "Imagens"
      %br/
      = form.file_field :images, multiple: true, style: "margin-top: 1rem"
    .actions
      = form.submit "Enviar", class: "button medium-button"

app/views/posts/_post.html.haml
%div{:id => "#{dom_id post}"}
  %p
    %strong Title:
    = post.title
  %p
    %strong Description:
    = post.description
  %p
    %strong Image:
    = image_tag post.image
  %p
    %strong Community participant:
    = post.community_participant_id

app/views/posts/edit.html.haml
.lists
  .my-communities
    .data-card
      %h1{style: "margin-bottom: 1.5rem;"} Editar anúncio
      = render "form", post: @post
      = link_to "Voltar", community_post_path(@community, @post), class: "button small-button"

app/views/posts/index.html.haml
%p{:style => "color: green"}= notice
%h1 Posts
#posts
  - @posts.each do |post|
    = render post
    %p
      = link_to "Show this post", community_post_path(@community, post)
= link_to "New post", new_community_post_path

= link_to 'Voltar para comunidades', community_path(@community)

app/views/posts/new.html.haml
.lists
  .my-communities
    .data-card
      %h1{style: "margin-bottom: 1.5rem;"} Criar anúncio
      = render "form", post: @post
      = link_to "Voltar", community_path(@community), class: "button small-button"

app/views/posts/show.html.haml
.lists
  .my-communities
    .data-card
      .post-header
        .post-header-info
          .user-info
            = image_tag resource_image(current_user), class: "medium-pfp"
            %h2.name
              = current_user.full_name
        .post-buttons
          - if !current_user.liked?(@post)
            = button_to community_post_likeds_path(@community, @post), class: "like-btn", method: :post, remote: true do
              %span Favoritar
              = image_tag("star.svg", class: "star-icon")
          - else
            = button_to community_post_liked_path(@community, @post, @liked), class: "like-btn", method: :delete, remote: true do
              %span Desfavoritar
              = image_tag("star.svg", class: "star-icon")
          - if current_user == @post.community_participant.user
            = link_to image_tag("pencil.svg", class: "pencil-edit", style: "margin-left: 1rem"), edit_community_post_path(@community, @post)
      .post-title
        %h2
          = @post.title
      .post-content
        = @post.description
      .post-images
        - @post.images.each do |image|
          = image_tag image
    #comments
      - @post.comments.each do |comment|
        .data-card.comment
          .user-info
            = image_tag resource_image(comment.user), class: "medium-pfp"
            %h2.name
              = comment.user.full_name
          .comment-content
            = comment.description
          - if current_user.is_admin || CommunityModder.where(user_id: current_user.id, community_id: @community.id).first.present?
            %div
              = button_to "delete", {:controller => :comments, :action => 'destroy', :community_id => @community.id, :post_id => @post.id, id: comment.id }, :method => :delete
    .add-comment.field
      = form_for [@community, @post, @comment], id: "new_comment", method: :post, remote: true do |f|
        = f.text_area :description, class: "input", placeholder: "Adicione um comentário", id: "comment_description"
        = f.submit "Enviar", class: "button medium-button", id: "comment_submit"