config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  resources :communities do
    resources :posts do
      resources :likeds
      resources :comments
    end
    resources :community_participants
  end

  put '/users/:id/update', to: 'users#update', as: 'update_user'

  get 'administration', to: 'administration#index'
  get 'administration/communities', to: 'administration#list_communities'
  patch 'administration/community/add_modder', to: 'administration#add_modder_to_community'
  get 'administration/admins', to: 'administration#list_admins'
  patch 'administration/admins/give_admin', to: 'administration#give_admin_permissions'
  patch 'administration/admins/remove_admin', to: 'administration#remove_admin_permissions'

  devise_for :users, controllers: {
    passwords: 'passwords'
  }
  
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  get 'dashboard', to: 'dashboard#index', as: 'dashboard'
  get 'dashboard/my_contents', to: 'dashboard#my_contents', as: 'my_contents'
  get 'dashboard/find_communities', to: 'dashboard#find_communities', as: 'find_communities'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/community.rb
class Community < ApplicationRecord
  has_one_attached :image
  has_many :community_participants, dependent: :destroy
  has_many :posts, through: :community_participants, source: :posts, dependent: :destroy
  has_many :community_modders, dependent: :destroy
  has_many :users, through: :community_modders
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: %i[ show edit update destroy ]
  before_action :set_community_participant, only: %i[ show edit update destroy ]

  # GET /communities or /communities.json
  def index
    logger.debug "#{current_user}"
    @communities = Community.all
  end

  # GET /communities/1 or /communities/1.json
  def show
    @posts = @community.posts
    @back_path = root_path
  end

  # GET /communities/new
  def new
    @community = Community.new
  end

  # GET /communities/1/edit
  def edit
  end

  # POST /communities or /communities.json
  def create
    @community = Community.new(community_params)

    respond_to do |format|
      if @community.save
        format.html { redirect_to administration_communities_path}
        format.json { render :show, status: :created, location: @community }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/1 or /communities/1.json
  def update
    respond_to do |format|
      if @community.update(community_params)
        format.html { redirect_to community_url(@community), notice: "Community was successfully updated." }
        format.json { render :show, status: :ok, location: @community }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1 or /communities/1.json
  def destroy
    @community.destroy

    respond_to do |format|
      format.html { redirect_to communities_url, notice: "Community was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      @community = Community.find(params[:id])
    end

    def set_community_participant
      logger.debug "#{current_user.id} #{params[:community_id]}"
      @community_participant = CommunityParticipant.where(community_id: params[:id], user_id: current_user.id).first
    end

    # Only allow a list of trusted parameters through.
    def community_params
      params.require(:community).permit(:name, :image)
    end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_community.html.haml
%div{:id => "#{dom_id community}"}
  %p
    %strong Nome:
    = community.name
  %p
    %strong Imagem:

app/views/communities/_form.html.haml
= form_with(model: community) do |form|
  - if community.errors.any?
    %div{:style => "color: red"}
      %h2
        = pluralize(community.errors.count, "error")
        proibiram esse registro de ser salvo
      %ul
        - community.errors.each do |error|
          %li= error.full_message
  %div
    = form.label :name, style: "display: block"
    = form.text_area :name
  %div
    = form.label :image, style: "display: block"
    = form.file_field :image
  %div
    = form.submit

app/views/communities/edit.html.haml
%h1 Editing community
= render "form", community: @community
%br/
%div
  = link_to "Mostrar comunidade", @community
  
  = link_to "Voltar para comunidade", communities_path

app/views/communities/index.html.haml
%p{:style => "color: green"}= notice
%h1 Communities
#communities
  - @communities.each do |community|
    = render community
    %p
      = link_to "Mostrar comunidade", community
= link_to "Nova comunidade", new_community_path

app/views/communities/new.html.haml
%h1 New community
= render "form", community: @community
%br/
%div
  = link_to "Voltar para comunidade", communities_path

app/views/communities/show.html.haml
.lists
  .my-communities
    %h2.title-posts
      = "#{@community.name} - Anúncios"
      = link_to image_tag("add_post.svg"), new_community_post_path(@community), class: "btn btn-primary"
    .cards-list
      - @posts.each do |post|
        .card{onclick: "window.location='#{community_post_path(@community, post)}'"}
          .card-image
            - if post.images.attached?
              = image_tag post.images.first
            - else
              = image_tag "post_default.png"
          .card-content
            %h3
              = post.title
            %p
              = post.community_participant.user.full_name